
### 🧹 DELETE msg by ID (existing)
DELETE http://localhost:3030/api/toy/68209dc13a12260960dac158/msg/ msgId

### 🧹 DELETE msg by ID (non-existing)
DELETE http://localhost:3030/api/toy/doesnotexist/msg/doesnotexist

### ➕ POST new msg (valid)
POST http://localhost:3030/api/toy/6824627096244be8aaa431a9/msg
Content-Type: application/json

{
    "txt": "Great Product!"
}

### ➕ POST new msg (missing name)
POST http://localhost:3030/api/toy/6824627096244be8aaa431a9/msg
Content-Type: application/json

{
    "price": 40
}
