
### 🧹 DELETE msg by ID (existing)
DELETE http://localhost:3030/api/toy/68209dc13a12260960dac158/msg/ msgId

### 🧹 DELETE msg by ID (non-existing)
DELETE http://localhost:3030/api/toy/doesnotexist/msg/doesnotexist

### ➕ POST new msg (valid)
POST http://localhost:3030/api/toy/msg
Content-Type: application/json

{
    "name": "Ocean Explorer",
    "price": 88,
    "inStock": true,
    "labels": ["Outdoor", "Box game"],
    "imgUrl": "https://example.com/ocean-explorer.jpg"
}

### ➕ POST new msg (missing name)
POST http://localhost:3030/api/toy/msg
Content-Type: application/json

{
    "price": 40,
    "inStock": true
}
